name: Publish Python Package

on:
  release:
    types: [created]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cibuildwheel
    - name: Build package
      run: |
        python3 -m cibuildwheel --output-dir dist
      env:
        CIBW_SKIP: "cp36-* cp37-* cp38-*"
        CIBW_ENVIRONMENT: "PIP_ONLY_BINARY=numpy"
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1